backend:
  name: git-gateway
  branch: master

media_folder: public/img
public_folder: img

collections:
  - name: "recipes"
    label: "Reseptit"
    folder: "content"
    create: true
    fields:
      - { label: "Nimi", name: "title", widget: "string" }
      - {
          label: "Ainesosat",
          name: "ingredients",
          widget: "list",
          fields:
            [
              { label: "Määrä", name: "quantity", widget: "number" },
              { label: "Yksikkö", name: "unit", widget: "string" },
              { label: "Ainesosa", name: "ingredient", widget: "string" },
            ],
        }
      - { label: "Ohje", name: "body", widget: "markdown" }
