backend:
  name: git-gateway
  branch: master

media_folder: public/img
public_folder: img

collections:
  - name: "recipes"
    label: "Reseptit"
    folder: "content"
    create: true
    fields:
      - { label: "Nimi", name: "title", widget: "string" }
      - {
          label: "Ainesosat",
          name: "ingredients",
          widget: "list",
          fields:
            [
              {
                label: "Määrä",
                name: "quantity",
                widget: "string",
                required: false,
              },
              {
                label: "Yksikkö",
                name: "unit",
                widget: "string",
                required: false,
              },
              { label: "Ainesosa", name: "ingredient", widget: "string" },
              {
                label: "Tarkenne",
                name: "details",
                widget: "string",
                required: false,
              },
            ],
        }
      - { label: "Ohje", name: "body", widget: "markdown" }
